[[pages]]
path = "home_page.py"
name = "Home"

[[pages]]
path = "rate_curves_page.py"
name = "Rate Curves"

[[pages]]
path = "rate_curve_surface.py"
name = "Rate Curve Surface"

[[pages]]
path = "rate_simulations_page.py"
name = "Rate Simulations"

[[pages]]
path = "treasury_inventory.py"
name = "Treasury Inventory"

[[pages]]
path = "treasury_risk.py"
name = "Treasury Risk"

[[pages]]
path = "interest_rate_page.py"
name = "Overnight Rates"

